// Curated, ORIGINAL SAT-style Math questions (NOT College Board content).
// These provide a clean, correctly-formatted fallback bank so the Math section,
// KaTeX rendering, and the Regression Trainer work immediately — before you run
// the vision importer over your official PDFs. Math uses inline LaTeX ($...$);
// data tables use markdown pipe syntax (rendered by MathText).

import type { SeedQuestion } from "./sampleQuestions";

export const CURATED_MATH: SeedQuestion[] = [
  // ---------------- Algebra ----------------
  {
    externalId: "curated-math-101",
    section: "MATH",
    domain: "Algebra",
    skill: "Linear inequalities",
    difficulty: "MEDIUM",
    format: "MCQ",
    stem: "Which of the following is the solution to the inequality $-3x + 5 \\le 14$?",
    correctAnswer: "B",
    explanation:
      "Subtract 5 from both sides: $-3x \\le 9$. Divide both sides by $-3$ and flip the inequality sign (dividing by a negative): $x \\ge -3$.",
    choices: [
      { label: "A", content: "$x \\le -3$", isCorrect: false, rationaleWrong: "The inequality sign must flip when dividing by a negative number." },
      { label: "B", content: "$x \\ge -3$", isCorrect: true },
      { label: "C", content: "$x \\le 3$", isCorrect: false, rationaleWrong: "This comes from $3x \\le 9$; the coefficient is $-3$, not $3$." },
      { label: "D", content: "$x \\ge 3$", isCorrect: false, rationaleWrong: "Sign and direction are both off." },
    ],
  },
  {
    externalId: "curated-math-102",
    section: "MATH",
    domain: "Algebra",
    skill: "Systems of two linear equations",
    difficulty: "MEDIUM",
    format: "SPR",
    stem: "If $\\begin{cases} 2x + y = 11 \\\\ x - y = 1 \\end{cases}$, what is the value of $x + y$?",
    correctAnswer: "7",
    explanation:
      "Add the equations to eliminate $y$: $(2x + y) + (x - y) = 11 + 1$, so $3x = 12$ and $x = 4$. Then $y = x - 1 = 3$. Therefore $x + y = 7$.",
    choices: [],
  },
  {
    externalId: "curated-math-103",
    section: "MATH",
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: "MEDIUM",
    format: "MCQ",
    stem: "A phone plan's monthly cost is given by $C = 0.10m + 15$, where $m$ is the number of minutes used. What does the number $15$ represent?",
    correctAnswer: "C",
    explanation:
      "In $C = 0.10m + 15$, the constant term $15$ is the value of $C$ when $m = 0$ — the fixed monthly cost that applies before any minutes are used.",
    choices: [
      { label: "A", content: "The cost per minute", isCorrect: false, rationaleWrong: "The cost per minute is the slope, $0.10$." },
      { label: "B", content: "The total cost for 15 minutes", isCorrect: false, rationaleWrong: "15 minutes would cost $0.10(15) + 15 = 16.50$." },
      { label: "C", content: "The fixed monthly fee", isCorrect: true },
      { label: "D", content: "The number of free minutes", isCorrect: false, rationaleWrong: "Nothing in the model describes free minutes." },
    ],
  },

  // ---------------- Advanced Math ----------------
  {
    externalId: "curated-math-104",
    section: "MATH",
    domain: "Advanced Math",
    skill: "Quadratics",
    difficulty: "MEDIUM",
    format: "MCQ",
    stem: "What are the solutions to the equation $x^2 - 5x + 6 = 0$?",
    correctAnswer: "B",
    explanation:
      "Factor: $x^2 - 5x + 6 = (x - 2)(x - 3) = 0$. Setting each factor to zero gives $x = 2$ and $x = 3$.",
    choices: [
      { label: "A", content: "$x = -2$ and $x = -3$", isCorrect: false, rationaleWrong: "These would come from $(x+2)(x+3)$, which expands to $x^2 + 5x + 6$." },
      { label: "B", content: "$x = 2$ and $x = 3$", isCorrect: true },
      { label: "C", content: "$x = 1$ and $x = 6$", isCorrect: false, rationaleWrong: "These multiply to 6 but sum to 7, not 5." },
      { label: "D", content: "$x = -1$ and $x = -6$", isCorrect: false, rationaleWrong: "These do not satisfy the equation." },
    ],
  },
  {
    externalId: "curated-math-105",
    section: "MATH",
    domain: "Advanced Math",
    skill: "Equivalent expressions",
    difficulty: "EASY",
    format: "MCQ",
    stem: "Which expression is equivalent to $\\dfrac{x^8}{x^3}$ for $x \\ne 0$?",
    correctAnswer: "A",
    explanation:
      "When dividing powers with the same base, subtract exponents: $\\dfrac{x^8}{x^3} = x^{8-3} = x^5$.",
    choices: [
      { label: "A", content: "$x^5$", isCorrect: true },
      { label: "B", content: "$x^{11}$", isCorrect: false, rationaleWrong: "Exponents are subtracted when dividing, not added." },
      { label: "C", content: "$x^{24}$", isCorrect: false, rationaleWrong: "Exponents are not multiplied when dividing." },
      { label: "D", content: "$x^2$", isCorrect: false, rationaleWrong: "$8 - 3 = 5$, not $2$." },
    ],
  },
  {
    externalId: "curated-math-106",
    section: "MATH",
    domain: "Advanced Math",
    skill: "Function notation",
    difficulty: "EASY",
    format: "SPR",
    stem: "The function $f$ is defined by $f(x) = 2x^2 - 3$. What is the value of $f(3)$?",
    correctAnswer: "15",
    explanation: "Substitute $x = 3$: $f(3) = 2(3)^2 - 3 = 2(9) - 3 = 18 - 3 = 15$.",
    choices: [],
  },
  {
    externalId: "curated-math-107",
    section: "MATH",
    domain: "Advanced Math",
    skill: "Exponential functions",
    difficulty: "HARD",
    format: "MCQ",
    stem: "The value of a car is modeled by $V = 24000(0.85)^t$, where $t$ is the number of years since purchase. Which statement best describes the meaning of $0.85$?",
    correctAnswer: "C",
    explanation:
      "In an exponential model $a\\cdot b^t$, a base of $0.85$ means the value is multiplied by $0.85$ each year — a 15% decrease per year, since $1 - 0.85 = 0.15$.",
    choices: [
      { label: "A", content: "The car loses \\$0.85 per year.", isCorrect: false, rationaleWrong: "Exponential models multiply; they do not subtract a fixed amount." },
      { label: "B", content: "The car's value increases by 85% each year.", isCorrect: false, rationaleWrong: "A base below 1 means the value decreases." },
      { label: "C", content: "The car loses 15% of its value each year.", isCorrect: true },
      { label: "D", content: "The car is worth 85% of \\$24000 after $t$ years.", isCorrect: false, rationaleWrong: "It is worth 85% of the previous year's value each year, compounding." },
    ],
  },
  {
    externalId: "curated-math-108",
    section: "MATH",
    domain: "Advanced Math",
    skill: "Nonlinear equations in one variable",
    difficulty: "MEDIUM",
    format: "SPR",
    stem: "If $\\sqrt{x + 7} = 5$, what is the value of $x$?",
    correctAnswer: "18",
    explanation: "Square both sides: $x + 7 = 25$. Subtract 7: $x = 18$. Check: $\\sqrt{18 + 7} = \\sqrt{25} = 5$.",
    choices: [],
  },

  // ---------------- Problem-Solving & Data Analysis ----------------
  {
    externalId: "curated-math-109",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Ratios, rates, proportions, units",
    difficulty: "EASY",
    format: "MCQ",
    stem: "At a store, 3 pounds of apples cost \\$7.50. At this rate, how much do 5 pounds of apples cost?",
    correctAnswer: "C",
    explanation:
      "The unit rate is $\\dfrac{7.50}{3} = 2.50$ dollars per pound. For 5 pounds: $5 \\times 2.50 = \\$12.50$.",
    choices: [
      { label: "A", content: "\\$10.00", isCorrect: false, rationaleWrong: "This uses \\$2.00 per pound, but the rate is \\$2.50 per pound." },
      { label: "B", content: "\\$11.25", isCorrect: false, rationaleWrong: "This is 4.5 pounds, not 5." },
      { label: "C", content: "\\$12.50", isCorrect: true },
      { label: "D", content: "\\$15.00", isCorrect: false, rationaleWrong: "This is the cost of 6 pounds." },
    ],
  },
  {
    externalId: "curated-math-110",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Percentages",
    difficulty: "MEDIUM",
    format: "MCQ",
    stem: "After a 20% increase, the price of a jacket is \\$60. What was the original price?",
    correctAnswer: "B",
    explanation:
      "A 20% increase means the new price is $1.20$ times the original: $1.20p = 60$. So $p = \\dfrac{60}{1.20} = 50$.",
    choices: [
      { label: "A", content: "\\$48", isCorrect: false, rationaleWrong: "This subtracts 20% of 60; the increase is on the original, not the new price." },
      { label: "B", content: "\\$50", isCorrect: true },
      { label: "C", content: "\\$72", isCorrect: false, rationaleWrong: "This adds 20% to \\$60 instead of reversing the increase." },
      { label: "D", content: "\\$40", isCorrect: false, rationaleWrong: "This would require a 50% increase to reach \\$60." },
    ],
  },
  {
    externalId: "curated-math-111",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Probability and conditional probability",
    difficulty: "MEDIUM",
    format: "MCQ",
    stimulus:
      "A bag contains colored marbles as shown in the table below.\n\n| Color | Number |\n| --- | --- |\n| Red | 4 |\n| Blue | 6 |\n| Green | 10 |",
    stem: "If one marble is selected at random, what is the probability that it is red?",
    correctAnswer: "A",
    explanation:
      "There are $4 + 6 + 10 = 20$ marbles total, of which 4 are red. The probability is $\\dfrac{4}{20} = \\dfrac{1}{5}$.",
    choices: [
      { label: "A", content: "$\\dfrac{1}{5}$", isCorrect: true },
      { label: "B", content: "$\\dfrac{1}{4}$", isCorrect: false, rationaleWrong: "This uses 16 as the total; the total is 20." },
      { label: "C", content: "$\\dfrac{2}{5}$", isCorrect: false, rationaleWrong: "This is the probability of blue." },
      { label: "D", content: "$\\dfrac{1}{2}$", isCorrect: false, rationaleWrong: "This is the probability of green." },
    ],
  },
  {
    externalId: "curated-math-112",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "One-variable data: distributions and measures",
    difficulty: "EASY",
    format: "SPR",
    stem: "What is the mean of the data set $\\{4, 8, 10, 14\\}$?",
    correctAnswer: "9",
    explanation: "The mean is the sum divided by the count: $\\dfrac{4 + 8 + 10 + 14}{4} = \\dfrac{36}{4} = 9$.",
    choices: [],
  },

  // ---------------- Geometry & Trigonometry ----------------
  {
    externalId: "curated-math-113",
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Circles",
    difficulty: "MEDIUM",
    format: "MCQ",
    stem: "A circle has an area of $36\\pi$ square centimeters. What is the radius of the circle, in centimeters?",
    correctAnswer: "B",
    explanation:
      "The area of a circle is $A = \\pi r^2$. Setting $\\pi r^2 = 36\\pi$ gives $r^2 = 36$, so $r = 6$.",
    choices: [
      { label: "A", content: "$3$", isCorrect: false, rationaleWrong: "$\\pi(3)^2 = 9\\pi$, not $36\\pi$." },
      { label: "B", content: "$6$", isCorrect: true },
      { label: "C", content: "$18$", isCorrect: false, rationaleWrong: "This is half of 36; the radius is $\\sqrt{36}$." },
      { label: "D", content: "$36$", isCorrect: false, rationaleWrong: "This is $r^2$, not $r$." },
    ],
  },
  {
    externalId: "curated-math-114",
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Right triangles and trigonometry",
    difficulty: "EASY",
    format: "SPR",
    stem: "A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?",
    correctAnswer: "10",
    explanation:
      "By the Pythagorean theorem, $c^2 = 6^2 + 8^2 = 36 + 64 = 100$, so $c = \\sqrt{100} = 10$.",
    choices: [],
  },
  {
    externalId: "curated-math-115",
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Right triangles and trigonometry",
    difficulty: "MEDIUM",
    format: "MCQ",
    stem: "In a right triangle, the side opposite angle $\\theta$ has length 5 and the hypotenuse has length 13. What is $\\sin \\theta$?",
    correctAnswer: "A",
    explanation:
      "By definition, $\\sin \\theta = \\dfrac{\\text{opposite}}{\\text{hypotenuse}} = \\dfrac{5}{13}$.",
    choices: [
      { label: "A", content: "$\\dfrac{5}{13}$", isCorrect: true },
      { label: "B", content: "$\\dfrac{12}{13}$", isCorrect: false, rationaleWrong: "This is $\\cos\\theta$ (adjacent over hypotenuse, where the adjacent leg is 12)." },
      { label: "C", content: "$\\dfrac{5}{12}$", isCorrect: false, rationaleWrong: "This is $\\tan\\theta$, opposite over adjacent." },
      { label: "D", content: "$\\dfrac{13}{5}$", isCorrect: false, rationaleWrong: "Sine of an acute angle cannot exceed 1." },
    ],
  },
  {
    externalId: "curated-math-116",
    section: "MATH",
    domain: "Geometry and Trigonometry",
    skill: "Area and volume",
    difficulty: "MEDIUM",
    format: "MCQ",
    stem: "A right circular cylinder has radius 3 and height 5. What is its volume?",
    correctAnswer: "C",
    explanation: "The volume of a cylinder is $V = \\pi r^2 h = \\pi (3)^2 (5) = 45\\pi$.",
    choices: [
      { label: "A", content: "$15\\pi$", isCorrect: false, rationaleWrong: "This uses $r$ instead of $r^2$." },
      { label: "B", content: "$30\\pi$", isCorrect: false, rationaleWrong: "This is the lateral surface area $2\\pi r h$, not the volume." },
      { label: "C", content: "$45\\pi$", isCorrect: true },
      { label: "D", content: "$225\\pi$", isCorrect: false, rationaleWrong: "This squares the height as well." },
    ],
  },

  // ---------------- Regression (isRegression) ----------------
  {
    externalId: "curated-reg-201",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Two-variable data: models and scatterplots",
    difficulty: "EASY",
    format: "MCQ",
    isRegression: true,
    desmosRelevant: true,
    stimulus:
      "The table shows the number of hours five students studied and their test scores.\n\n| Hours ($x$) | Score ($y$) |\n| --- | --- |\n| 1 | 62 |\n| 2 | 68 |\n| 4 | 79 |\n| 6 | 88 |\n| 8 | 95 |",
    stem: "Which choice best describes the association between hours studied and test score?",
    correctAnswer: "A",
    explanation:
      "As the hours studied ($x$) increase, the test scores ($y$) increase as well, and they climb by roughly the same amount each time. This is a positive, approximately linear association.",
    choices: [
      { label: "A", content: "A positive linear association", isCorrect: true },
      { label: "B", content: "A negative linear association", isCorrect: false, rationaleWrong: "A negative association would mean scores decrease as hours increase." },
      { label: "C", content: "No association", isCorrect: false, rationaleWrong: "The scores clearly rise with hours, so there is an association." },
      { label: "D", content: "An exponential association", isCorrect: false, rationaleWrong: "The score increases by a roughly constant amount, not a constant ratio." },
    ],
  },
  {
    externalId: "curated-reg-202",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Regression / line of best fit",
    difficulty: "MEDIUM",
    format: "MCQ",
    isRegression: true,
    desmosRelevant: true,
    stem: "A line of best fit for a data set relating hours studied $x$ to test score $y$ is $\\hat{y} = 4.5x + 58$. Which statement best interprets the slope, $4.5$?",
    correctAnswer: "B",
    explanation:
      "In a line of best fit $\\hat{y} = mx + b$, the slope $m$ is the predicted change in $y$ for each one-unit increase in $x$. Here, each additional hour of studying is associated with a predicted increase of about 4.5 points.",
    choices: [
      { label: "A", content: "A student who studies 0 hours is predicted to score 4.5.", isCorrect: false, rationaleWrong: "The predicted score at $x=0$ is the intercept, 58, not the slope." },
      { label: "B", content: "Each additional hour studied predicts about 4.5 more points.", isCorrect: true },
      { label: "C", content: "Every student's score increases by exactly 4.5 points per hour.", isCorrect: false, rationaleWrong: "A line of best fit gives a predicted trend, not an exact rule for every student." },
      { label: "D", content: "The maximum possible score is 4.5.", isCorrect: false, rationaleWrong: "The slope is a rate of change, not a maximum." },
    ],
  },
  {
    externalId: "curated-reg-203",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Regression / line of best fit",
    difficulty: "MEDIUM",
    format: "MCQ",
    isRegression: true,
    desmosRelevant: true,
    stem: "The line of best fit for a data set is $\\hat{y} = 4.5x + 58$, where $x$ is hours studied and $y$ is test score. What does the value $58$ represent?",
    correctAnswer: "C",
    explanation:
      "The intercept $b = 58$ is the predicted value of $y$ when $x = 0$ — the predicted test score for a student who studies 0 hours.",
    choices: [
      { label: "A", content: "The score increases by 58 points per hour.", isCorrect: false, rationaleWrong: "That would be the slope, which is 4.5." },
      { label: "B", content: "The highest score any student earned.", isCorrect: false, rationaleWrong: "The intercept is a prediction at $x=0$, not a maximum from the data." },
      { label: "C", content: "The predicted score for a student who studies 0 hours.", isCorrect: true },
      { label: "D", content: "The number of students in the study.", isCorrect: false, rationaleWrong: "The intercept has nothing to do with sample size." },
    ],
  },
  {
    externalId: "curated-reg-204",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Regression / line of best fit",
    difficulty: "MEDIUM",
    format: "SPR",
    isRegression: true,
    desmosRelevant: true,
    stem: "Using the model $\\hat{y} = 2.5x + 30$, what is the predicted value of $y$ when $x = 8$?",
    correctAnswer: "50",
    explanation: "Substitute $x = 8$: $\\hat{y} = 2.5(8) + 30 = 20 + 30 = 50$.",
    choices: [],
  },
  {
    externalId: "curated-reg-205",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Two-variable data: models and scatterplots",
    difficulty: "MEDIUM",
    format: "MCQ",
    isRegression: true,
    desmosRelevant: true,
    stem: "A data set relating two variables has a correlation coefficient of $r = -0.92$. Which choice best describes the relationship?",
    correctAnswer: "D",
    explanation:
      "The correlation coefficient $r$ ranges from $-1$ to $1$. A value near $-1$ (like $-0.92$) indicates a strong, negative linear relationship: as one variable increases, the other tends to decrease.",
    choices: [
      { label: "A", content: "A weak positive relationship", isCorrect: false, rationaleWrong: "A negative $r$ indicates a negative, not positive, relationship." },
      { label: "B", content: "A strong positive relationship", isCorrect: false, rationaleWrong: "The sign of $r$ is negative." },
      { label: "C", content: "No relationship", isCorrect: false, rationaleWrong: "An $r$ near $-1$ indicates a strong relationship, not none." },
      { label: "D", content: "A strong negative relationship", isCorrect: true },
    ],
  },
  {
    externalId: "curated-reg-206",
    section: "MATH",
    domain: "Problem-Solving and Data Analysis",
    skill: "Regression / line of best fit",
    difficulty: "HARD",
    format: "MCQ",
    isRegression: true,
    desmosRelevant: true,
    stem: "A line of best fit predicts a value of $68$ for a data point whose actual observed value is $72$. What is the residual for this data point, and what does it indicate?",
    correctAnswer: "A",
    explanation:
      "A residual is the actual value minus the predicted value: $72 - 68 = 4$. A positive residual means the actual value is above the prediction, so the model underpredicted this point.",
    choices: [
      { label: "A", content: "$4$; the actual value is above the predicted value.", isCorrect: true },
      { label: "B", content: "$-4$; the model overpredicted the value.", isCorrect: false, rationaleWrong: "Residual is actual minus predicted: $72 - 68 = +4$, not $-4$." },
      { label: "C", content: "$4$; the model overpredicted the value.", isCorrect: false, rationaleWrong: "A positive residual means the model underpredicted, not overpredicted." },
      { label: "D", content: "$140$; the sum of the two values.", isCorrect: false, rationaleWrong: "A residual is a difference, not a sum." },
    ],
  },
];
